spring.application.name=resumemanager
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.profiles.active=${PROFILE}
thirdeye.resume.updater.api.key=${THIRDEYE_RESUME_UPDATER_API_KEY}
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=true
thirdeye.timezone = Asia/Kolkata

spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=2

thirdeye.redis.balance-prefix=user:tokens:
thirdeye.redis.resume-prefix=resume:buffer:

spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
spring.cloud.aws.region.static=ap-south-1
thirdeye.bucket.name=${AWS_BUCKET_NAME}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB 

thirdeye.message.broker.read.rate=10000
thirdeye.messagebroker.topics.textextracter.topicName=textextracter
thirdeye.messagebroker.topics.textextracter.topicKey=${TEXTEXTRACTER_KEY}
thirdeye.messagebroker.topics.aiprocesser.topicName=aiprocesser
thirdeye.messagebroker.topics.aiprocesser.topicKey=${AI_PROCESSER_KEY}
thirdeye.messagebroker.topics.statusupdater.topicName=statusupdater
thirdeye.messagebroker.topics.statusupdater.topicKey=${STATUS_UPDATER_KEY}
thirdeye.maximumqueries=10
